name: Pytest Lint

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - "test-linting"

jobs:
  pytest-lint:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v4

    - uses: actions/setup-python@v4
      with:
        python-version: '3.12'
        cache: 'pip'

    - name: Set up virtual environment in /tests-functional/
      run: |
        python -m venv tests-functional/.venv
        echo "tests-functional/.venv/bin" >> $GITHUB_PATH  # Add virtualenv to PATH for subsequent steps

    - name: Install dependencies based on requirements.txt
      run: pip install -r tests-functional/requirements.txt

    - name: Run pytest-lint
      run: pre-commit run --all-files --verbose --config tests-functional/.pre-commit-config.yaml
